### ISSUE TITLE
panic: device ATmega32U4 not found in package descriptor

### ISSUE THREAD

**Issue by Blu3wolf** [clevabit/as2make#1]
Im trying to use this to generate a makefile for an atmel studio project: https://github.com/uriba107/fcc_controller

Ive specified the --project, --toolchain-prefix=AVR, and --dfp-sdk. It reports Loading the project file, then loading the 'DPF' package descriptor, then panics that the device ATmega32U4 is not found in the package descriptor. 

Is this operation unsupported, or am I doing something wrong?

**Comment by Blu3wolf** [comment]
Renaming the device in the cproj file is correctly detected. Renaming the .pdsc file is correctly detected. Current suspicion of where a bug might lie is the packageDesc code that decodes the xml data. sdk.go, lines 102 onwards.

**Comment by noctarius** [comment]
Hey @Blu3wolf, at the moment the detection is super simple and was only tested on our own projects (which all use a SAMD21). Happy to extend the algorithms though :-)

I'll have a look at the project probably on Thursday. If you want to help, feel free to send in a PR!

Thanks for testing and your interest!

**Comment by noctarius** [comment]
I just had a quick look, and I could imagine that the issue is, that the tool currently expects an arm based toolchain, but the atmega uses an avr toolchain. Guess it just needs to be added as a valid toolchain type :)

**Comment by Blu3wolf** [comment]
While that is possibly an error, that seems not to be where this error is coming from. The error in question is from line 67 of sdk.go, and the function Device() is called only the once it seems, on line 127 of build.go. 

The name seems to be getting passed correctly to Device(), as it is named correctly in the error message. I guess Ill try to build this locally, and add some debug messages - I wonder whether its as simple as the xml not being decoded correctly on line 62.

**Comment by Blu3wolf** [comment]
From adding debug messages, it seems that dfp.packageDesc.Devices.Family.Devices has a length of zero elements when it is iterated over on line 62 of sdk.go. So it presumably is not being populated correctly before this point.

**Comment by Blu3wolf** [comment]
Okay, line 47 is being reached: its calling packageDesc, err := loadPackageDescriptor(sdkPath), and then err is != nil. So it just returns an empty SDK struct instead of telling us the error.

**Comment by Blu3wolf** [comment]
And its hitting line 108 in loadPackageDescriptor(): So it is opening the file and reading it successfully, but gets an error in decoding - which returns an empty Package{} to dfp.packageDesc, who just ignores the error and continues.

**Comment by noctarius** [comment]
Just woke up, but thanks for additional information and time spent. What is the specific dfp package necessary for your mpu? I guess the xml is "successfully" read, but its structure doesn't match the deserialized strict. In go this is not an error in itself, since it supports partial deserialization.

**Comment by noctarius** [comment]
I think it would be the normal ATMEGA DFP (second download at http://packs.download.atmel.com/) wouldn't it? That structure looks actually good at first glance. I'll quickly try to load the project after breakfast.

The project in question if fcc_controller/Fcc3, isn't it?

**Comment by Blu3wolf** [comment]
Thats right - ATmega_DFP.1.7.374 is the one I have, and fcc_controller/Fcc3 is the project in question. 

Trying to print the error gives me a cryptic error about strconv.ParseInt: parsing "0x80": invalid syntax.

**Comment by noctarius** [comment]
Perfect, I'll have a look. Already know that the .cproj file is different, using avrgcc elements instead of armgcc. Means latest at that point it'd fail anyway :)

**Comment by Blu3wolf** [comment]
I figured that was probably the case - the readme was pretty clear that its a minimal implementation at this point. I was just going to try fix one error at a time until it worked, but this first one still has me stumped. Im totally new to Go and XML.

**Comment by noctarius** [comment]
Ok good catch so far :-) I return err=nil in case the xml cannot be deserialized, instead of returning the error instance. And yes, the error is probably a not wide enough data type for a specific field in the struct (hence the parseInt error).

First two issues are fixed and pushed. Now the interesting part around the avrgcc element :)

**Comment by Blu3wolf** [comment]
well, now it generates a makefile and makedep file. However, as you say the paths for the avr-gcc tool are not correct. It seems like it would be easier to define CC at the top, and call $(CC) rather than having the full path to the tool in each call. 

I guess Ill have a go at tidying the generated file up and see if it works.

EDIT: its also output -I includes to the DFP folder/samd21a/include.

**Comment by noctarius** [comment]
Please update your local version and try to run it :) Afterwards it'd be great to see a diff of the original makefile and the generated one.

**Comment by Blu3wolf** [comment]
By original, you mean the one generated by atmel studio? Unfortunately I am not on windows and dont have a makefile which works for linux... hence my interest in this project :)

**Comment by noctarius** [comment]
The samd21a include is a good catch. Looking into where to get that dynamically.
For the makefile, no worries, I'll load the project upstairs :)

**Comment by Blu3wolf** [comment]
I guess I need to tell it where to find the toolchain - its looking in as2make/-/bin/avr-gcc now. I was hoping for a path more like avr-gcc seeing as I have it in my PATH.

**Comment by Blu3wolf** [comment]
`Building file: /home/blue/Downloads/fcc_controller-180601/fcc_controller-180601/src/Controller/Fcc3/Descriptors.c
cc1: error: unrecognized command-line option '-mthumb'
cc1: error: unrecognized command-line option '-mlong-calls'
cc1: error: unrecognized command-line option '-mcpu=avr8'
make: *** [Makefile:198: /home/blue/Downloads/fcc_controller-180601/fcc_controller-180601/src/Controller/Fcc3/Descriptors.o] Error 1
`
I dont think avr-gcc knows those options.

**Comment by noctarius** [comment]
Yeah you have to give it the bin directory of your toolchain right now. It doesn't try to resolve it from PATH at the moment.

Just pushed a new version which removes the hardcoded samd include path.

For your just arrived comment. Ouch, ok that seems to get a bit more complicated ;) I'll get back to it later today. Need to get something else done for now. Thanks for the help though! Appreciate it.

**Comment by Blu3wolf** [comment]
Thank you so much for working on this. Im learning lots!

**Comment by noctarius** [comment]
Hey there, sorry for the wait but I just finished adjusting the generator and the project compiles and links. Not sure if the generated image works though, but I'd expect it :)

Can you try the new commit?

**Comment by Blu3wolf** [comment]
well, it has built the fcc3controller.elf so I guess that is this specific issue resolved - thank you very much. Bunch of compiler warnings, but for all I know that might be normal for this project. Ill have a go with this and see if it works, and Ill report back if Ive got any further errors with as2make. Thanks for extending your project for me!

**Comment by Blu3wolf** [comment]
Closed by d9a405ab13acfd409b8b159fe5bfe98268e031d0
